// <auto-generated />
using System;
using CalculusApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculusApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250318151416_AddExtraParameters")]
    partial class AddExtraParameters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("CalculusApp.Models.ExpressionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Expression")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstExtraParameter")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondExtraParameter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solution")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExpressionHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
